[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ashes_fg"
version = "0.1.0"
description = "Analog Synthesis for High Level Systems (ASHES)"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "verilog-parser",
    "lxml",
]

[tool.setuptools.packages.find]
include = ["ashes_fg*"]