# Package Information
[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "ASHES"
version = "1.6"
dependencies = [
  "numpy",
  "shapely",
  "verilog-parser",
  "lxml",

  "argparse",
  "gdstk"
]

[project.scripts]
ashes = "ashes_fg.cli:main"
gen_stdcell_defs = "ashes_fg.gds_to_celldef.gen_stdcell_defs:main"
