grid 0.05um 0.05um
snap user
load "../../../ASHES-Skywater130nm/sky130_cells/Cap_Bank/Cap_Bank.mag"
gds write "../../examples/mag2stdcells/mag2gds/Cap_Bank.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/ESD_Diode/sky130_hilas_VinjDiodeProtect01Copy.mag"
gds write "../../examples/mag2stdcells/mag2gds/sky130_hilas_VinjDiodeProtect01Copy.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/G_or_S_IndrctSwcs/G_or_S_IndrctSwcs.mag"
gds write "../../examples/mag2stdcells/mag2gds/G_or_S_IndrctSwcs.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirctGswc_OutMat/IndirectGswc_OutMat.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectGswc_OutMat.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_4x1/IndirectVMM_4x1.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectVMM_4x1.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_4x2/IndirectVMM_4x2_ashes.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectVMM_4x2_ashes.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_4x2/IndirectVMM_4x2.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectVMM_4x2.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_Bot_Bmat_4x2/IndirectGswc_OutMat.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectGswc_OutMat.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_Bot_Bmat_4x2/IndirectVMM_4x2.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectVMM_4x2.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_Bot_Bmat_4x2/IndirectVMM_Bot_Bmat_4x2.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectVMM_Bot_Bmat_4x2.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_GSwcs_1x2/IndirectVMM_GSwcs_1x2.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectVMM_GSwcs_1x2.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_Top_AorBmat_4x2/G_or_S_IndrctSwcs.mag"
gds write "../../examples/mag2stdcells/mag2gds/G_or_S_IndrctSwcs.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/IndirectVMM_Top_AorBmat_4x2/IndirectVMM_Top_AorBmat_4x2.mag"
gds write "../../examples/mag2stdcells/mag2gds/IndirectVMM_Top_AorBmat_4x2.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Pcells/NMOS_150x420nm.mag"
gds write "../../examples/mag2stdcells/mag2gds/NMOS_150x420nm.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Pcells/NMOS_500x420nm.mag"
gds write "../../examples/mag2stdcells/mag2gds/NMOS_500x420nm.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Pcells/NMOS_HV_500x1300nm.mag"
gds write "../../examples/mag2stdcells/mag2gds/NMOS_HV_500x1300nm.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Pcells/PMOS_150x420nm.mag"
gds write "../../examples/mag2stdcells/mag2gds/PMOS_150x420nm.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Pcells/PMOS_HV_500x2000.mag"
gds write "../../examples/mag2stdcells/mag2gds/PMOS_HV_500x2000.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Pcells/PMOS_HV_500x2000nm.mag"
gds write "../../examples/mag2stdcells/mag2gds/PMOS_HV_500x2000nm.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Pcells/PMOS_HV_minSize.mag"
gds write "../../examples/mag2stdcells/mag2gds/PMOS_HV_minSize.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Sblock/S_Block_east.mag"
gds write "../../examples/mag2stdcells/mag2gds/S_Block_east.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Sblock/S_Block_filler_off_diagonal.mag"
gds write "../../examples/mag2stdcells/mag2gds/S_Block_filler_off_diagonal.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Sblock/S_Block.mag"
gds write "../../examples/mag2stdcells/mag2gds/S_Block.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Sblock/S_Block_NS_routing_diagonal.mag"
gds write "../../examples/mag2stdcells/mag2gds/S_Block_NS_routing_diagonal.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Sblock/S_Block_test.mag"
gds write "../../examples/mag2stdcells/mag2gds/S_Block_test.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/Sblock/S_Block_west.mag"
gds write "../../examples/mag2stdcells/mag2gds/S_Block_west.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/TA_FGbias_1x2/TA_FGbias_1x2_ashes.mag"
gds write "../../examples/mag2stdcells/mag2gds/TA_FGbias_1x2_ashes.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/TA_FGbias_1x2/TA_FGbias_1x2.mag"
gds write "../../examples/mag2stdcells/mag2gds/TA_FGbias_1x2.gds"
load "../../../ASHES-Skywater130nm/sky130_cells/TGate_2nMirror/TGate_2nMirror.mag"
gds write "../../examples/mag2stdcells/mag2gds/TGate_2nMirror.gds"
quit -noprompt
