module TOP(port1);


	/* Island 0 */
	TSMC350nm_4x2_Indirect I__0 (.island_num(0), .row(0), .col(0), .matrix_row(2), .matrix_col(6), .matrix_row(2), .matrix_col(6));
	Tgate_swc_fr_Kernel_Horiz_top_edge I__1 (.island_num(0), .row(0), .col(6), .matrix_row(1), .matrix_col(1));
	Tgate_swc_fr_Kernel_Horiz_bot_edge I__2 (.island_num(0), .row(1), .col(6), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_top I__3 (.island_num(0), .row(0), .col(7), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_core I__4 (.island_num(0), .row(1), .col(7), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_start I__5 (.island_num(0), .row(0), .col(8), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_core I__6 (.island_num(0), .row(0), .col(9), .matrix_row(1), .matrix_col(3), .matrix_row(1), .matrix_col(3));
	Integration_fr_AvgPool_core I__7 (.island_num(0), .row(1), .col(8), .matrix_row(1), .matrix_col(4), .matrix_row(1), .matrix_col(4));
	AvgPool_n_Relu I__8 (.island_num(0), .row(0), .col(12), .matrix_row(2), .matrix_col(1), .matrix_row(2), .matrix_col(1));
	TSMC350nm_4x2_Indirect I__9 (.island_num(0), .row(2), .col(0), .matrix_row(2), .matrix_col(6), .matrix_row(2), .matrix_col(6));
	Tgate_swc_fr_Kernel_Horiz_top_edge I__10 (.island_num(0), .row(2), .col(6), .matrix_row(1), .matrix_col(1));
	Tgate_swc_fr_Kernel_Horiz_bot_edge I__11 (.island_num(0), .row(3), .col(6), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_top I__12 (.island_num(0), .row(2), .col(7), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_core I__13 (.island_num(0), .row(3), .col(7), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_start I__14 (.island_num(0), .row(2), .col(8), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_core I__15 (.island_num(0), .row(2), .col(9), .matrix_row(1), .matrix_col(3), .matrix_row(1), .matrix_col(3));
	Integration_fr_AvgPool_core I__16 (.island_num(0), .row(3), .col(8), .matrix_row(1), .matrix_col(4), .matrix_row(1), .matrix_col(4));
	AvgPool_n_Relu I__17 (.island_num(0), .row(2), .col(12), .matrix_row(2), .matrix_col(1), .matrix_row(2), .matrix_col(1));
	TSMC350nm_4x2_Indirect I__18 (.island_num(0), .row(4), .col(0), .matrix_row(2), .matrix_col(6), .matrix_row(2), .matrix_col(6));
	Tgate_swc_fr_Kernel_Horiz_top_edge I__19 (.island_num(0), .row(4), .col(6), .matrix_row(1), .matrix_col(1));
	Tgate_swc_fr_Kernel_Horiz_bot_edge I__20 (.island_num(0), .row(5), .col(6), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_top I__21 (.island_num(0), .row(4), .col(7), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_core I__22 (.island_num(0), .row(5), .col(7), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_start I__23 (.island_num(0), .row(4), .col(8), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_core I__24 (.island_num(0), .row(4), .col(9), .matrix_row(1), .matrix_col(3), .matrix_row(1), .matrix_col(3));
	Integration_fr_AvgPool_core I__25 (.island_num(0), .row(5), .col(8), .matrix_row(1), .matrix_col(4), .matrix_row(1), .matrix_col(4));
	AvgPool_n_Relu I__26 (.island_num(0), .row(4), .col(12), .matrix_row(2), .matrix_col(1), .matrix_row(2), .matrix_col(1));
	TSMC350nm_4x2_Indirect I__27 (.island_num(0), .row(6), .col(0), .matrix_row(2), .matrix_col(6), .matrix_row(2), .matrix_col(6));
	Tgate_swc_fr_Kernel_Horiz_top_edge I__28 (.island_num(0), .row(6), .col(6), .matrix_row(1), .matrix_col(1));
	Tgate_swc_fr_Kernel_Horiz_bot_edge I__29 (.island_num(0), .row(7), .col(6), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_top I__30 (.island_num(0), .row(6), .col(7), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_core I__31 (.island_num(0), .row(7), .col(7), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_start I__32 (.island_num(0), .row(6), .col(8), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_core I__33 (.island_num(0), .row(6), .col(9), .matrix_row(1), .matrix_col(3), .matrix_row(1), .matrix_col(3));
	Integration_fr_AvgPool_core I__34 (.island_num(0), .row(7), .col(8), .matrix_row(1), .matrix_col(4), .matrix_row(1), .matrix_col(4));
	AvgPool_n_Relu I__35 (.island_num(0), .row(6), .col(12), .matrix_row(2), .matrix_col(1), .matrix_row(2), .matrix_col(1));
	TSMC350nm_4x2_Indirect I__36 (.island_num(0), .row(8), .col(0), .matrix_row(2), .matrix_col(6), .matrix_row(2), .matrix_col(6));
	Tgate_swc_fr_Kernel_Horiz_top_edge I__37 (.island_num(0), .row(8), .col(6), .matrix_row(1), .matrix_col(1));
	Tgate_swc_fr_Kernel_Horiz_bot_edge I__38 (.island_num(0), .row(9), .col(6), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_top I__39 (.island_num(0), .row(8), .col(7), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_core I__40 (.island_num(0), .row(9), .col(7), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_start I__41 (.island_num(0), .row(8), .col(8), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_core I__42 (.island_num(0), .row(8), .col(9), .matrix_row(1), .matrix_col(3), .matrix_row(1), .matrix_col(3));
	Integration_fr_AvgPool_core I__43 (.island_num(0), .row(9), .col(8), .matrix_row(1), .matrix_col(4), .matrix_row(1), .matrix_col(4));
	AvgPool_n_Relu I__44 (.island_num(0), .row(8), .col(12), .matrix_row(2), .matrix_col(1), .matrix_row(2), .matrix_col(1));
	TSMC350nm_4x2_Indirect I__45 (.island_num(0), .row(10), .col(0), .matrix_row(2), .matrix_col(6), .matrix_row(2), .matrix_col(6));
	Tgate_swc_fr_Kernel_Horiz_top_edge I__46 (.island_num(0), .row(10), .col(6), .matrix_row(1), .matrix_col(1));
	Tgate_swc_fr_Kernel_Horiz_bot_edge I__47 (.island_num(0), .row(11), .col(6), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_top I__48 (.island_num(0), .row(10), .col(7), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_core I__49 (.island_num(0), .row(11), .col(7), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_start I__50 (.island_num(0), .row(10), .col(8), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_core I__51 (.island_num(0), .row(10), .col(9), .matrix_row(1), .matrix_col(3), .matrix_row(1), .matrix_col(3));
	Integration_fr_AvgPool_core I__52 (.island_num(0), .row(11), .col(8), .matrix_row(1), .matrix_col(4), .matrix_row(1), .matrix_col(4));
	AvgPool_n_Relu I__53 (.island_num(0), .row(10), .col(12), .matrix_row(2), .matrix_col(1), .matrix_row(2), .matrix_col(1));
	TSMC350nm_4x2_Indirect I__54 (.island_num(0), .row(12), .col(0), .matrix_row(2), .matrix_col(6), .matrix_row(2), .matrix_col(6));
	Tgate_swc_fr_Kernel_Horiz_top_edge I__55 (.island_num(0), .row(12), .col(6), .matrix_row(1), .matrix_col(1));
	Tgate_swc_fr_Kernel_Horiz_bot_edge I__56 (.island_num(0), .row(13), .col(6), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_top I__57 (.island_num(0), .row(12), .col(7), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_core I__58 (.island_num(0), .row(13), .col(7), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_start I__59 (.island_num(0), .row(12), .col(8), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_core I__60 (.island_num(0), .row(12), .col(9), .matrix_row(1), .matrix_col(3), .matrix_row(1), .matrix_col(3));
	Integration_fr_AvgPool_core I__61 (.island_num(0), .row(13), .col(8), .matrix_row(1), .matrix_col(4), .matrix_row(1), .matrix_col(4));
	AvgPool_n_Relu I__62 (.island_num(0), .row(12), .col(12), .matrix_row(2), .matrix_col(1), .matrix_row(2), .matrix_col(1));
	TSMC350nm_4x2_Indirect I__63 (.island_num(0), .row(14), .col(0), .matrix_row(2), .matrix_col(6), .matrix_row(2), .matrix_col(6));
	Tgate_swc_fr_Kernel_Horiz_top_edge I__64 (.island_num(0), .row(14), .col(6), .matrix_row(1), .matrix_col(1));
	Tgate_swc_fr_Kernel_Horiz_bot_edge I__65 (.island_num(0), .row(15), .col(6), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_top I__66 (.island_num(0), .row(14), .col(7), .matrix_row(1), .matrix_col(1));
	I_Subtractor_AvgPool_core I__67 (.island_num(0), .row(15), .col(7), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_start I__68 (.island_num(0), .row(14), .col(8), .matrix_row(1), .matrix_col(1));
	Integration_fr_AvgPool_core I__69 (.island_num(0), .row(14), .col(9), .matrix_row(1), .matrix_col(3), .matrix_row(1), .matrix_col(3));
	Integration_fr_AvgPool_core I__70 (.island_num(0), .row(15), .col(8), .matrix_row(1), .matrix_col(4), .matrix_row(1), .matrix_col(4));
	AvgPool_n_Relu I__71 (.island_num(0), .row(14), .col(12), .matrix_row(2), .matrix_col(1), .matrix_row(2), .matrix_col(1));

 	/*Programming Mux */ 
	TSMC350nm_VinjDecode2to4_htile decoder(.island_num(0), .direction(horizontal), .bits(4));
	TSMC350nm_IndirectSwitches switch(.island_num(0), .direction(horizontal), .num(6));
	TSMC350nm_VinjDecode2to4_vtile decoder(.island_num(0), .direction(vertical), .bits(6));
	TSMC350nm_drainSelect01d3 switch(.island_num(0), .direction(vertical), .num(16), .type(drain_select));
	TSMC350nm_FourTgate_ThickOx_FG_MEM switch(.island_num(0), .direction(vertical), .num(16), .type(prog_switch));

 endmodule